"""initial AutoFlow schema

Revision ID: 6973a8314ce3
Revises:
Create Date: 2026-08-19 20:57:33.247445
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '6973a8314ce3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=True),
    sa.Column('tax_id', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'TRIAL', 'SUSPENDED', 'CANCELLED')", name=op.f('ck_companies_ck_companies_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies')),
    sa.UniqueConstraint('tax_id', name=op.f('uq_companies_tax_id'))
    )
    op.create_index(op.f('ix_companies_created_at'), 'companies', ['created_at'], unique=False)
    op.create_index(op.f('ix_companies_slug'), 'companies', ['slug'], unique=True)
    op.create_index(op.f('ix_companies_status'), 'companies', ['status'], unique=False)
    op.create_table('task_outbox',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('task_name', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=190), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('attempts >= 0', name=op.f('ck_task_outbox_ck_task_outbox_attempts')),
    sa.CheckConstraint("status IN ('PENDING','DISPATCHED')", name=op.f('ck_task_outbox_ck_task_outbox_status')),
    sa.CheckConstraint("task_name IN ('process_message','send_whatsapp_message','generate_summary','password_reset_email','process_appointment','send_notification')", name=op.f('ck_task_outbox_ck_task_outbox_task_name')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_task_outbox_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_outbox')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_task_outbox_idempotency_key'))
    )
    op.create_index(op.f('ix_task_outbox_available_at'), 'task_outbox', ['available_at'], unique=False)
    op.create_index(op.f('ix_task_outbox_company_id'), 'task_outbox', ['company_id'], unique=False)
    op.create_index(op.f('ix_task_outbox_created_at'), 'task_outbox', ['created_at'], unique=False)
    op.create_index('ix_task_outbox_pending', 'task_outbox', ['status', 'available_at', 'id'], unique=False)
    op.create_index(op.f('ix_task_outbox_status'), 'task_outbox', ['status'], unique=False)
    op.create_index(op.f('ix_task_outbox_task_name'), 'task_outbox', ['task_name'], unique=False)
    op.create_table('ai_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assistant_name', sa.String(length=100), nullable=False),
    sa.Column('personality', sa.Text(), nullable=True),
    sa.Column('tone', sa.String(length=80), nullable=False),
    sa.Column('greeting_message', sa.Text(), nullable=True),
    sa.Column('after_hours_message', sa.Text(), nullable=True),
    sa.Column('rules', sa.Text(), nullable=True),
    sa.Column('commercial_instructions', sa.Text(), nullable=True),
    sa.Column('transfer_instructions', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('history_limit', sa.Integer(), nullable=False),
    sa.Column('summary_threshold', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_reply_enabled', sa.Boolean(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('history_limit > 0', name=op.f('ck_ai_settings_ck_ai_settings_history')),
    sa.CheckConstraint('max_tokens > 0', name=op.f('ck_ai_settings_ck_ai_settings_max_tokens')),
    sa.CheckConstraint('temperature >= 0 AND temperature <= 2', name=op.f('ck_ai_settings_ck_ai_settings_temperature')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_ai_settings_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_settings')),
    sa.UniqueConstraint('company_id', name='uq_ai_settings_company')
    )
    op.create_index(op.f('ix_ai_settings_company_id'), 'ai_settings', ['company_id'], unique=False)
    op.create_index(op.f('ix_ai_settings_created_at'), 'ai_settings', ['created_at'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('phone_normalized', sa.String(length=24), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('organization', sa.String(length=160), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('crm_stage', sa.String(length=24), nullable=False),
    sa.Column('opportunity_title', sa.String(length=180), nullable=True),
    sa.Column('opportunity_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('next_action', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('preferences', sa.JSON(), nullable=False),
    sa.Column('last_interaction_at', sa.DateTime(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("crm_stage IN ('NOVO','INTERESSADO','QUALIFICADO','PROPOSTA','VENDA','PERDIDO')", name=op.f('ck_customers_ck_customers_crm_stage')),
    sa.CheckConstraint('opportunity_value IS NULL OR opportunity_value >= 0', name=op.f('ck_customers_ck_customers_opportunity_value')),
    sa.CheckConstraint("status IN ('ACTIVE','INACTIVE','BLOCKED')", name=op.f('ck_customers_ck_customers_status')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_customers_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers')),
    sa.UniqueConstraint('company_id', 'phone_normalized', name='uq_customer_company_phone')
    )
    op.create_index('ix_customer_company_name', 'customers', ['company_id', 'name'], unique=False)
    op.create_index('ix_customer_company_stage', 'customers', ['company_id', 'crm_stage'], unique=False)
    op.create_index(op.f('ix_customers_company_id'), 'customers', ['company_id'], unique=False)
    op.create_index(op.f('ix_customers_created_at'), 'customers', ['created_at'], unique=False)
    op.create_index(op.f('ix_customers_crm_stage'), 'customers', ['crm_stage'], unique=False)
    op.create_index(op.f('ix_customers_last_interaction_at'), 'customers', ['last_interaction_at'], unique=False)
    op.create_index(op.f('ix_customers_status'), 'customers', ['status'], unique=False)
    op.create_table('delivery_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('neighborhood', sa.String(length=120), nullable=True),
    sa.Column('postal_code_start', sa.String(length=8), nullable=True),
    sa.Column('postal_code_end', sa.String(length=8), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('free_shipping', sa.Boolean(), nullable=False),
    sa.Column('minimum_order', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('min_delivery_days', sa.Integer(), nullable=False),
    sa.Column('max_delivery_days', sa.Integer(), nullable=False),
    sa.Column('pickup_available', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('min_delivery_days >= 0 AND max_delivery_days >= min_delivery_days', name=op.f('ck_delivery_rules_ck_delivery_days')),
    sa.CheckConstraint('minimum_order >= 0', name=op.f('ck_delivery_rules_ck_delivery_minimum')),
    sa.CheckConstraint('price >= 0', name=op.f('ck_delivery_rules_ck_delivery_price')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_delivery_rules_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_delivery_rules'))
    )
    op.create_index('ix_delivery_company_location', 'delivery_rules', ['company_id', 'city', 'neighborhood', 'is_active'], unique=False)
    op.create_index(op.f('ix_delivery_rules_city'), 'delivery_rules', ['city'], unique=False)
    op.create_index(op.f('ix_delivery_rules_company_id'), 'delivery_rules', ['company_id'], unique=False)
    op.create_index(op.f('ix_delivery_rules_created_at'), 'delivery_rules', ['created_at'], unique=False)
    op.create_index(op.f('ix_delivery_rules_is_active'), 'delivery_rules', ['is_active'], unique=False)
    op.create_index(op.f('ix_delivery_rules_neighborhood'), 'delivery_rules', ['neighborhood'], unique=False)
    op.create_index(op.f('ix_delivery_rules_postal_code_end'), 'delivery_rules', ['postal_code_end'], unique=False)
    op.create_index(op.f('ix_delivery_rules_postal_code_start'), 'delivery_rules', ['postal_code_start'], unique=False)
    op.create_table('faqs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_faqs_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_faqs'))
    )
    op.create_index('ix_faq_company_active', 'faqs', ['company_id', 'is_active', 'category'], unique=False)
    op.create_index(op.f('ix_faqs_category'), 'faqs', ['category'], unique=False)
    op.create_index(op.f('ix_faqs_company_id'), 'faqs', ['company_id'], unique=False)
    op.create_index(op.f('ix_faqs_created_at'), 'faqs', ['created_at'], unique=False)
    op.create_index(op.f('ix_faqs_is_active'), 'faqs', ['is_active'], unique=False)
    op.create_table('knowledge_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('PROCESSING','READY','FAILED')", name=op.f('ck_knowledge_documents_ck_knowledge_status')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_knowledge_documents_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_documents')),
    sa.UniqueConstraint('company_id', 'checksum', name='uq_knowledge_checksum')
    )
    op.create_index('ix_knowledge_company_active', 'knowledge_documents', ['company_id', 'is_active', 'status'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_checksum'), 'knowledge_documents', ['checksum'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_company_id'), 'knowledge_documents', ['company_id'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_created_at'), 'knowledge_documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_is_active'), 'knowledge_documents', ['is_active'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_status'), 'knowledge_documents', ['status'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sku', sa.String(length=80), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('promotional_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('price >= 0', name=op.f('ck_products_ck_products_price')),
    sa.CheckConstraint('promotional_price IS NULL OR promotional_price >= 0', name=op.f('ck_products_ck_products_promotional_price')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_products_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('company_id', 'sku', name='uq_product_company_sku')
    )
    op.create_index('ix_product_company_category', 'products', ['company_id', 'category'], unique=False)
    op.create_index('ix_product_company_name', 'products', ['company_id', 'name'], unique=False)
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_company_id'), 'products', ['company_id'], unique=False)
    op.create_index(op.f('ix_products_created_at'), 'products', ['created_at'], unique=False)
    op.create_index(op.f('ix_products_is_active'), 'products', ['is_active'], unique=False)
    op.create_table('professionals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('color', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_professionals_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_professionals')),
    sa.UniqueConstraint('company_id', 'email', name='uq_professional_company_email'),
    sa.UniqueConstraint('id', 'company_id', name='uq_professional_id_company')
    )
    op.create_index(op.f('ix_professionals_company_id'), 'professionals', ['company_id'], unique=False)
    op.create_index(op.f('ix_professionals_created_at'), 'professionals', ['created_at'], unique=False)
    op.create_index(op.f('ix_professionals_is_active'), 'professionals', ['is_active'], unique=False)
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('buffer_minutes', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('buffer_minutes >= 0', name=op.f('ck_services_ck_service_buffer')),
    sa.CheckConstraint('duration_minutes > 0', name=op.f('ck_services_ck_service_duration')),
    sa.CheckConstraint('price >= 0', name=op.f('ck_services_ck_service_price')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_services_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_services')),
    sa.UniqueConstraint('company_id', 'name', name='uq_service_company_name'),
    sa.UniqueConstraint('id', 'company_id', name='uq_service_id_company')
    )
    op.create_index(op.f('ix_services_company_id'), 'services', ['company_id'], unique=False)
    op.create_index(op.f('ix_services_created_at'), 'services', ['created_at'], unique=False)
    op.create_index(op.f('ix_services_is_active'), 'services', ['is_active'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=False),
    sa.Column('tag_type', sa.String(length=24), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("tag_type IN ('GENERAL','CUSTOMER','CONVERSATION')", name=op.f('ck_tags_ck_tags_type')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_tags_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('company_id', 'name', 'tag_type', name='uq_tag_company_name_type')
    )
    op.create_index(op.f('ix_tags_company_id'), 'tags', ['company_id'], unique=False)
    op.create_index(op.f('ix_tags_created_at'), 'tags', ['created_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('password_reset_at', sa.DateTime(), nullable=True),
    sa.Column('reset_token_hash', sa.String(length=128), nullable=True),
    sa.Column('reset_token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('active_company_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['active_company_id'], ['companies.id'], name=op.f('fk_users_active_company_id_companies'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_active'), 'users', ['active'], unique=False)
    op.create_index(op.f('ix_users_active_company_id'), 'users', ['active_company_id'], unique=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_reset_token_hash'), 'users', ['reset_token_hash'], unique=False)
    op.create_table('whatsapp_integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_phone_number', sa.String(length=32), nullable=True),
    sa.Column('phone_number_id', sa.String(length=100), nullable=False),
    sa.Column('business_account_id', sa.String(length=100), nullable=True),
    sa.Column('access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('app_secret_encrypted', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_webhook_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('PENDING','CONNECTED','ERROR','DISCONNECTED')", name=op.f('ck_whatsapp_integrations_ck_whatsapp_status')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_whatsapp_integrations_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_whatsapp_integrations')),
    sa.UniqueConstraint('company_id', name='uq_whatsapp_company')
    )
    op.create_index(op.f('ix_whatsapp_integrations_business_account_id'), 'whatsapp_integrations', ['business_account_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_integrations_company_id'), 'whatsapp_integrations', ['company_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_integrations_created_at'), 'whatsapp_integrations', ['created_at'], unique=False)
    op.create_index(op.f('ix_whatsapp_integrations_is_active'), 'whatsapp_integrations', ['is_active'], unique=False)
    op.create_index(op.f('ix_whatsapp_integrations_phone_number_id'), 'whatsapp_integrations', ['phone_number_id'], unique=True)
    op.create_index(op.f('ix_whatsapp_integrations_status'), 'whatsapp_integrations', ['status'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('professional_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('external_reference', sa.String(length=190), nullable=True),
    sa.Column('idempotency_key', sa.String(length=190), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=255), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('PENDING','CONFIRMED','COMPLETED','CANCELLED','NO_SHOW')", name=op.f('ck_appointments_ck_appointments_status')),
    sa.CheckConstraint('ends_at > starts_at', name=op.f('ck_appointments_ck_appointments_window')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_appointments_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_appointments_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_appointments_customer_id_customers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], name=op.f('fk_appointments_professional_id_professionals'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_appointments_service_id_services'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointments')),
    sa.UniqueConstraint('company_id', 'idempotency_key', name='uq_appointment_idempotency')
    )
    op.create_index('ix_appointment_company_status', 'appointments', ['company_id', 'status'], unique=False)
    op.create_index('ix_appointment_professional_window', 'appointments', ['company_id', 'professional_id', 'starts_at', 'ends_at'], unique=False)
    op.create_index(op.f('ix_appointments_company_id'), 'appointments', ['company_id'], unique=False)
    op.create_index(op.f('ix_appointments_created_at'), 'appointments', ['created_at'], unique=False)
    op.create_index(op.f('ix_appointments_created_by_user_id'), 'appointments', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_appointments_customer_id'), 'appointments', ['customer_id'], unique=False)
    op.create_index(op.f('ix_appointments_ends_at'), 'appointments', ['ends_at'], unique=False)
    op.create_index(op.f('ix_appointments_professional_id'), 'appointments', ['professional_id'], unique=False)
    op.create_index(op.f('ix_appointments_service_id'), 'appointments', ['service_id'], unique=False)
    op.create_index(op.f('ix_appointments_starts_at'), 'appointments', ['starts_at'], unique=False)
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    op.create_table('audit_logs',
    sa.Column(
        'id',
        sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
        autoincrement=True,
        nullable=False,
    ),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_logs_actor_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_audit_logs_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_company_entity', 'audit_logs', ['company_id', 'entity_type', 'entity_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_company_id'), 'audit_logs', ['company_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_table('business_hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('professional_id', sa.Integer(), nullable=True),
    sa.Column('weekday', sa.SmallInteger(), nullable=False),
    sa.Column('opens_at', sa.Time(), nullable=True),
    sa.Column('closes_at', sa.Time(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('is_closed = 1 OR (opens_at IS NOT NULL AND closes_at IS NOT NULL AND opens_at < closes_at)', name=op.f('ck_business_hours_ck_business_hours_window')),
    sa.CheckConstraint('weekday BETWEEN 0 AND 6', name=op.f('ck_business_hours_ck_business_hours_weekday')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_business_hours_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], name=op.f('fk_business_hours_professional_id_professionals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_hours')),
    sa.UniqueConstraint('company_id', 'professional_id', 'weekday', name='uq_business_hour_scope_weekday')
    )
    op.create_index(op.f('ix_business_hours_company_id'), 'business_hours', ['company_id'], unique=False)
    op.create_index('ix_business_hours_company_weekday', 'business_hours', ['company_id', 'weekday'], unique=False)
    op.create_index(op.f('ix_business_hours_created_at'), 'business_hours', ['created_at'], unique=False)
    op.create_index(op.f('ix_business_hours_professional_id'), 'business_hours', ['professional_id'], unique=False)
    op.create_table('company_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('invited_at', sa.DateTime(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("role IN ('OWNER', 'ADMIN', 'AGENT')", name=op.f('ck_company_members_ck_company_members_role')),
    sa.CheckConstraint("status IN ('INVITED', 'ACTIVE', 'DISABLED')", name=op.f('ck_company_members_ck_company_members_status')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_company_members_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_company_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_members')),
    sa.UniqueConstraint('company_id', 'user_id', name='uq_member_company_user')
    )
    op.create_index(op.f('ix_company_members_company_id'), 'company_members', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_members_created_at'), 'company_members', ['created_at'], unique=False)
    op.create_index(op.f('ix_company_members_user_id'), 'company_members', ['user_id'], unique=False)
    op.create_index('ix_member_company_role', 'company_members', ['company_id', 'role'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('assigned_user_id', sa.Integer(), nullable=True),
    sa.Column('whatsapp_integration_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=24), nullable=False),
    sa.Column('external_id', sa.String(length=190), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('ai_status', sa.String(length=24), nullable=False),
    sa.Column('human_requested', sa.Boolean(), nullable=False),
    sa.Column('unread_count', sa.Integer(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('memory', sa.JSON(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("ai_status IN ('ACTIVE','PAUSED','DISABLED')", name=op.f('ck_conversations_ck_conversations_ai_status')),
    sa.CheckConstraint("status IN ('OPEN','PENDING','RESOLVED','CLOSED')", name=op.f('ck_conversations_ck_conversations_status')),
    sa.CheckConstraint('unread_count >= 0', name=op.f('ck_conversations_ck_conversations_unread')),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], name=op.f('fk_conversations_assigned_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_conversations_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_conversations_customer_id_customers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['whatsapp_integration_id'], ['whatsapp_integrations.id'], name=op.f('fk_conversations_whatsapp_integration_id_whatsapp_integrations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations')),
    sa.UniqueConstraint('company_id', 'channel', 'external_id', name='uq_conversation_external')
    )
    op.create_index('ix_conversation_company_last', 'conversations', ['company_id', 'last_message_at'], unique=False)
    op.create_index('ix_conversation_company_status', 'conversations', ['company_id', 'status'], unique=False)
    op.create_index(op.f('ix_conversations_ai_status'), 'conversations', ['ai_status'], unique=False)
    op.create_index(op.f('ix_conversations_assigned_user_id'), 'conversations', ['assigned_user_id'], unique=False)
    op.create_index(op.f('ix_conversations_company_id'), 'conversations', ['company_id'], unique=False)
    op.create_index(op.f('ix_conversations_created_at'), 'conversations', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversations_customer_id'), 'conversations', ['customer_id'], unique=False)
    op.create_index(op.f('ix_conversations_last_message_at'), 'conversations', ['last_message_at'], unique=False)
    op.create_index(op.f('ix_conversations_status'), 'conversations', ['status'], unique=False)
    op.create_index(op.f('ix_conversations_whatsapp_integration_id'), 'conversations', ['whatsapp_integration_id'], unique=False)
    op.create_table('customer_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_customer_tags_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_customer_tags_customer_id_customers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_customer_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_tags')),
    sa.UniqueConstraint('company_id', 'customer_id', 'tag_id', name='uq_customer_tag')
    )
    op.create_index(op.f('ix_customer_tags_company_id'), 'customer_tags', ['company_id'], unique=False)
    op.create_index(op.f('ix_customer_tags_created_at'), 'customer_tags', ['created_at'], unique=False)
    op.create_index(op.f('ix_customer_tags_customer_id'), 'customer_tags', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_tags_tag_id'), 'customer_tags', ['tag_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('notification_type', sa.String(length=48), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('link_url', sa.String(length=500), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=190), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_notifications_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    sa.UniqueConstraint('company_id', 'idempotency_key', name='uq_notification_idempotency')
    )
    op.create_index('ix_notification_company_created', 'notifications', ['company_id', 'created_at'], unique=False)
    op.create_index('ix_notification_user_unread', 'notifications', ['company_id', 'user_id', 'is_read'], unique=False)
    op.create_index(op.f('ix_notifications_company_id'), 'notifications', ['company_id'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('product_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=True),
    sa.Column('color', sa.String(length=80), nullable=True),
    sa.Column('size', sa.String(length=80), nullable=True),
    sa.Column('sku', sa.String(length=80), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('price IS NULL OR price >= 0', name=op.f('ck_product_variants_ck_variants_price')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_product_variants_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_variants_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_variants')),
    sa.UniqueConstraint('company_id', 'sku', name='uq_variant_company_sku')
    )
    op.create_index(op.f('ix_product_variants_color'), 'product_variants', ['color'], unique=False)
    op.create_index(op.f('ix_product_variants_company_id'), 'product_variants', ['company_id'], unique=False)
    op.create_index(op.f('ix_product_variants_created_at'), 'product_variants', ['created_at'], unique=False)
    op.create_index(op.f('ix_product_variants_is_active'), 'product_variants', ['is_active'], unique=False)
    op.create_index(op.f('ix_product_variants_product_id'), 'product_variants', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_variants_size'), 'product_variants', ['size'], unique=False)
    op.create_index('ix_variant_product_options', 'product_variants', ['product_id', 'color', 'size'], unique=False)
    op.create_table('professional_services',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('professional_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['professional_id', 'company_id'], ['professionals.id', 'professionals.company_id'], name='fk_professional_services_professional_tenant', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id', 'company_id'], ['services.id', 'services.company_id'], name='fk_professional_services_service_tenant', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'professional_id', 'service_id', name=op.f('pk_professional_services'))
    )
    op.create_index('ix_professional_services_company', 'professional_services', ['company_id'], unique=False)
    op.create_table('schedule_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('professional_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('all_day', sa.Boolean(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('ends_at > starts_at', name=op.f('ck_schedule_blocks_ck_schedule_blocks_window')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_schedule_blocks_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], name=op.f('fk_schedule_blocks_professional_id_professionals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedule_blocks'))
    )
    op.create_index('ix_schedule_block_company_window', 'schedule_blocks', ['company_id', 'starts_at', 'ends_at'], unique=False)
    op.create_index(op.f('ix_schedule_blocks_company_id'), 'schedule_blocks', ['company_id'], unique=False)
    op.create_index(op.f('ix_schedule_blocks_created_at'), 'schedule_blocks', ['created_at'], unique=False)
    op.create_index(op.f('ix_schedule_blocks_ends_at'), 'schedule_blocks', ['ends_at'], unique=False)
    op.create_index(op.f('ix_schedule_blocks_professional_id'), 'schedule_blocks', ['professional_id'], unique=False)
    op.create_index(op.f('ix_schedule_blocks_starts_at'), 'schedule_blocks', ['starts_at'], unique=False)
    op.create_table('conversation_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_conversation_tags_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_conversation_tags_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_conversation_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_tags')),
    sa.UniqueConstraint('company_id', 'conversation_id', 'tag_id', name='uq_conversation_tag')
    )
    op.create_index(op.f('ix_conversation_tags_company_id'), 'conversation_tags', ['company_id'], unique=False)
    op.create_index(op.f('ix_conversation_tags_conversation_id'), 'conversation_tags', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_tags_created_at'), 'conversation_tags', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversation_tags_tag_id'), 'conversation_tags', ['tag_id'], unique=False)
    op.create_table('inventories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reserved_quantity', sa.Integer(), nullable=False),
    sa.Column('minimum_quantity', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('minimum_quantity >= 0', name=op.f('ck_inventories_ck_inventory_minimum')),
    sa.CheckConstraint('(product_id IS NOT NULL AND variant_id IS NULL) OR (product_id IS NULL AND variant_id IS NOT NULL)', name=op.f('ck_inventories_ck_inventory_catalog_item')),
    sa.CheckConstraint('quantity >= 0', name=op.f('ck_inventories_ck_inventory_quantity')),
    sa.CheckConstraint('reserved_quantity >= 0 AND reserved_quantity <= quantity', name=op.f('ck_inventories_ck_inventory_reserved')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_inventories_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_inventories_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], name=op.f('fk_inventories_variant_id_product_variants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventories')),
    sa.UniqueConstraint('company_id', 'product_id', name='uq_inventory_product')
    )
    op.create_index(op.f('ix_inventories_company_id'), 'inventories', ['company_id'], unique=False)
    op.create_index(op.f('ix_inventories_created_at'), 'inventories', ['created_at'], unique=False)
    op.create_index(op.f('ix_inventories_product_id'), 'inventories', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventories_variant_id'), 'inventories', ['variant_id'], unique=True)
    op.create_index('ix_inventory_company_low', 'inventories', ['company_id', 'quantity', 'minimum_quantity'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('sender_user_id', sa.Integer(), nullable=True),
    sa.Column('reply_to_id', sa.Integer(), nullable=True),
    sa.Column('external_message_id', sa.String(length=190), nullable=True),
    sa.Column('idempotency_key', sa.String(length=190), nullable=True),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('sender_type', sa.String(length=16), nullable=False),
    sa.Column('message_type', sa.String(length=24), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('processing_status', sa.String(length=24), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('ai_metadata', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("direction IN ('INBOUND','OUTBOUND','SYSTEM')", name=op.f('ck_messages_ck_messages_direction')),
    sa.CheckConstraint("processing_status IN ('PENDING','PROCESSING','PROCESSED','SKIPPED','FAILED')", name=op.f('ck_messages_ck_messages_processing')),
    sa.CheckConstraint("sender_type IN ('CUSTOMER','AI','AGENT','SYSTEM')", name=op.f('ck_messages_ck_messages_sender_type')),
    sa.CheckConstraint("status IN ('RECEIVED','QUEUED','SENDING','SENT','DELIVERED','READ','FAILED')", name=op.f('ck_messages_ck_messages_status')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_messages_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_messages_customer_id_customers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reply_to_id'], ['messages.id'], name=op.f('fk_messages_reply_to_id_messages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], name=op.f('fk_messages_sender_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages')),
    sa.UniqueConstraint('company_id', 'external_message_id', name='uq_message_external'),
    sa.UniqueConstraint('company_id', 'idempotency_key', name='uq_message_idempotency')
    )
    op.create_index('ix_message_company_status', 'messages', ['company_id', 'status'], unique=False)
    op.create_index('ix_message_conversation_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_messages_company_id'), 'messages', ['company_id'], unique=False)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_customer_id'), 'messages', ['customer_id'], unique=False)
    op.create_index(op.f('ix_messages_reply_to_id'), 'messages', ['reply_to_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_user_id'), 'messages', ['sender_user_id'], unique=False)
    op.create_index(op.f('ix_messages_status'), 'messages', ['status'], unique=False)
    op.create_table('inventory_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('movement_type', sa.String(length=16), nullable=False),
    sa.Column('quantity_delta', sa.Integer(), nullable=False),
    sa.Column('quantity_before', sa.Integer(), nullable=False),
    sa.Column('quantity_after', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('reference_type', sa.String(length=64), nullable=True),
    sa.Column('reference_id', sa.String(length=100), nullable=True),
    sa.Column('idempotency_key', sa.String(length=190), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("movement_type IN ('IN','OUT','ADJUSTMENT','RESERVE','RELEASE')", name=op.f('ck_inventory_movements_ck_inventory_movement_type')),
    sa.CheckConstraint('quantity_before >= 0 AND quantity_after >= 0', name=op.f('ck_inventory_movements_ck_inventory_movement_balances')),
    sa.CheckConstraint('quantity_delta <> 0', name=op.f('ck_inventory_movements_ck_inventory_movement_delta')),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_inventory_movements_actor_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_inventory_movements_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventories.id'], name=op.f('fk_inventory_movements_inventory_id_inventories'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_movements')),
    sa.UniqueConstraint('company_id', 'idempotency_key', name='uq_inventory_movement_idempotency')
    )
    op.create_index(op.f('ix_inventory_movements_actor_user_id'), 'inventory_movements', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_company_id'), 'inventory_movements', ['company_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_created_at'), 'inventory_movements', ['created_at'], unique=False)
    op.create_index(op.f('ix_inventory_movements_inventory_id'), 'inventory_movements', ['inventory_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_movement_type'), 'inventory_movements', ['movement_type'], unique=False)
    op.create_index('ix_movement_inventory_created', 'inventory_movements', ['inventory_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_movement_inventory_created', table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_movement_type'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_inventory_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_created_at'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_company_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_actor_user_id'), table_name='inventory_movements')
    op.drop_table('inventory_movements')
    op.drop_index(op.f('ix_messages_status'), table_name='messages')
    op.drop_index(op.f('ix_messages_sender_user_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_reply_to_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_customer_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_company_id'), table_name='messages')
    op.drop_index('ix_message_conversation_created', table_name='messages')
    op.drop_index('ix_message_company_status', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_inventory_company_low', table_name='inventories')
    op.drop_index(op.f('ix_inventories_variant_id'), table_name='inventories')
    op.drop_index(op.f('ix_inventories_product_id'), table_name='inventories')
    op.drop_index(op.f('ix_inventories_created_at'), table_name='inventories')
    op.drop_index(op.f('ix_inventories_company_id'), table_name='inventories')
    op.drop_table('inventories')
    op.drop_index(op.f('ix_conversation_tags_tag_id'), table_name='conversation_tags')
    op.drop_index(op.f('ix_conversation_tags_created_at'), table_name='conversation_tags')
    op.drop_index(op.f('ix_conversation_tags_conversation_id'), table_name='conversation_tags')
    op.drop_index(op.f('ix_conversation_tags_company_id'), table_name='conversation_tags')
    op.drop_table('conversation_tags')
    op.drop_index(op.f('ix_schedule_blocks_starts_at'), table_name='schedule_blocks')
    op.drop_index(op.f('ix_schedule_blocks_professional_id'), table_name='schedule_blocks')
    op.drop_index(op.f('ix_schedule_blocks_ends_at'), table_name='schedule_blocks')
    op.drop_index(op.f('ix_schedule_blocks_created_at'), table_name='schedule_blocks')
    op.drop_index(op.f('ix_schedule_blocks_company_id'), table_name='schedule_blocks')
    op.drop_index('ix_schedule_block_company_window', table_name='schedule_blocks')
    op.drop_table('schedule_blocks')
    op.drop_index('ix_professional_services_company', table_name='professional_services')
    op.drop_table('professional_services')
    op.drop_index('ix_variant_product_options', table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_size'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_product_id'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_is_active'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_created_at'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_company_id'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_color'), table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_company_id'), table_name='notifications')
    op.drop_index('ix_notification_user_unread', table_name='notifications')
    op.drop_index('ix_notification_company_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_customer_tags_tag_id'), table_name='customer_tags')
    op.drop_index(op.f('ix_customer_tags_customer_id'), table_name='customer_tags')
    op.drop_index(op.f('ix_customer_tags_created_at'), table_name='customer_tags')
    op.drop_index(op.f('ix_customer_tags_company_id'), table_name='customer_tags')
    op.drop_table('customer_tags')
    op.drop_index(op.f('ix_conversations_whatsapp_integration_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_status'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_last_message_at'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_customer_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_created_at'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_company_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_assigned_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_ai_status'), table_name='conversations')
    op.drop_index('ix_conversation_company_status', table_name='conversations')
    op.drop_index('ix_conversation_company_last', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('ix_member_company_role', table_name='company_members')
    op.drop_index(op.f('ix_company_members_user_id'), table_name='company_members')
    op.drop_index(op.f('ix_company_members_created_at'), table_name='company_members')
    op.drop_index(op.f('ix_company_members_company_id'), table_name='company_members')
    op.drop_table('company_members')
    op.drop_index(op.f('ix_business_hours_professional_id'), table_name='business_hours')
    op.drop_index(op.f('ix_business_hours_created_at'), table_name='business_hours')
    op.drop_index('ix_business_hours_company_weekday', table_name='business_hours')
    op.drop_index(op.f('ix_business_hours_company_id'), table_name='business_hours')
    op.drop_table('business_hours')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_company_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('ix_audit_company_entity', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_starts_at'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_service_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_professional_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_ends_at'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_customer_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_created_by_user_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_created_at'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_company_id'), table_name='appointments')
    op.drop_index('ix_appointment_professional_window', table_name='appointments')
    op.drop_index('ix_appointment_company_status', table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_whatsapp_integrations_status'), table_name='whatsapp_integrations')
    op.drop_index(op.f('ix_whatsapp_integrations_phone_number_id'), table_name='whatsapp_integrations')
    op.drop_index(op.f('ix_whatsapp_integrations_is_active'), table_name='whatsapp_integrations')
    op.drop_index(op.f('ix_whatsapp_integrations_created_at'), table_name='whatsapp_integrations')
    op.drop_index(op.f('ix_whatsapp_integrations_company_id'), table_name='whatsapp_integrations')
    op.drop_index(op.f('ix_whatsapp_integrations_business_account_id'), table_name='whatsapp_integrations')
    op.drop_table('whatsapp_integrations')
    op.drop_index(op.f('ix_users_reset_token_hash'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index(op.f('ix_users_active_company_id'), table_name='users')
    op.drop_index(op.f('ix_users_active'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tags_created_at'), table_name='tags')
    op.drop_index(op.f('ix_tags_company_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_services_is_active'), table_name='services')
    op.drop_index(op.f('ix_services_created_at'), table_name='services')
    op.drop_index(op.f('ix_services_company_id'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_professionals_is_active'), table_name='professionals')
    op.drop_index(op.f('ix_professionals_created_at'), table_name='professionals')
    op.drop_index(op.f('ix_professionals_company_id'), table_name='professionals')
    op.drop_table('professionals')
    op.drop_index(op.f('ix_products_is_active'), table_name='products')
    op.drop_index(op.f('ix_products_created_at'), table_name='products')
    op.drop_index(op.f('ix_products_company_id'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_index('ix_product_company_name', table_name='products')
    op.drop_index('ix_product_company_category', table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_knowledge_documents_status'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_is_active'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_created_at'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_company_id'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_checksum'), table_name='knowledge_documents')
    op.drop_index('ix_knowledge_company_active', table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    op.drop_index(op.f('ix_faqs_is_active'), table_name='faqs')
    op.drop_index(op.f('ix_faqs_created_at'), table_name='faqs')
    op.drop_index(op.f('ix_faqs_company_id'), table_name='faqs')
    op.drop_index(op.f('ix_faqs_category'), table_name='faqs')
    op.drop_index('ix_faq_company_active', table_name='faqs')
    op.drop_table('faqs')
    op.drop_index(op.f('ix_delivery_rules_postal_code_start'), table_name='delivery_rules')
    op.drop_index(op.f('ix_delivery_rules_postal_code_end'), table_name='delivery_rules')
    op.drop_index(op.f('ix_delivery_rules_neighborhood'), table_name='delivery_rules')
    op.drop_index(op.f('ix_delivery_rules_is_active'), table_name='delivery_rules')
    op.drop_index(op.f('ix_delivery_rules_created_at'), table_name='delivery_rules')
    op.drop_index(op.f('ix_delivery_rules_company_id'), table_name='delivery_rules')
    op.drop_index(op.f('ix_delivery_rules_city'), table_name='delivery_rules')
    op.drop_index('ix_delivery_company_location', table_name='delivery_rules')
    op.drop_table('delivery_rules')
    op.drop_index(op.f('ix_customers_status'), table_name='customers')
    op.drop_index(op.f('ix_customers_last_interaction_at'), table_name='customers')
    op.drop_index(op.f('ix_customers_crm_stage'), table_name='customers')
    op.drop_index(op.f('ix_customers_created_at'), table_name='customers')
    op.drop_index(op.f('ix_customers_company_id'), table_name='customers')
    op.drop_index('ix_customer_company_stage', table_name='customers')
    op.drop_index('ix_customer_company_name', table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_ai_settings_created_at'), table_name='ai_settings')
    op.drop_index(op.f('ix_ai_settings_company_id'), table_name='ai_settings')
    op.drop_table('ai_settings')
    op.drop_index(op.f('ix_task_outbox_task_name'), table_name='task_outbox')
    op.drop_index(op.f('ix_task_outbox_status'), table_name='task_outbox')
    op.drop_index('ix_task_outbox_pending', table_name='task_outbox')
    op.drop_index(op.f('ix_task_outbox_created_at'), table_name='task_outbox')
    op.drop_index(op.f('ix_task_outbox_company_id'), table_name='task_outbox')
    op.drop_index(op.f('ix_task_outbox_available_at'), table_name='task_outbox')
    op.drop_table('task_outbox')
    op.drop_index(op.f('ix_companies_status'), table_name='companies')
    op.drop_index(op.f('ix_companies_slug'), table_name='companies')
    op.drop_index(op.f('ix_companies_created_at'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
